# Generated by Django 4.2.5 on 2023-09-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'admin_table',
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=50)),
                ('age', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'donor_table',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('non-gov', 'non governmental'), ('gov', 'governmental')], max_length=100)),
                ('address', models.TextField(max_length=300)),
                ('password', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'organisation_table',
            },
        ),
    ]
