# Generated by Django 4.2.5 on 2023-10-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='orgaimage',
            field=models.FileField(default='no image found', upload_to='organisationimage'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='age',
            field=models.IntegerField(),
        ),
    ]
