# Generated by Django 4.2.5 on 2023-10-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_organisation_orgaimage_alter_donor_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='orgaimage',
            field=models.FileField(upload_to='organisationimage'),
        ),
    ]
