# Generated by Django 4.2.5 on 2023-10-12 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_organisation_orgaimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donororgmapping',
            fields=[
                ('mappingid', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.donor')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.organisation')),
            ],
            options={
                'db_table': 'donororgmapping_table',
            },
        ),
    ]
